packages:
  - "."
  - "examples/*"
  - "../xstate-duckdb"
  - "../xstate-nats"


ignoredBuiltDependencies:
  - esbuild

overrides:
  "@jr200/xstate-duckdb": "workspace:*"
  "@jr200/xstate-nats": "workspace:*"
